### PR TITLE
update TOC to use tabular figures

### PR DESCRIPTION
**Pull request by aforsythe**

### CODE REVIEW

**Comment by thomasmansencal** [comment]
Not sure what this does but shouldn't the command be `ccTabularNums`? I also notice that we don't use the same number of spaces for tabs and [this line](https://github.com/ves-tech/cinematiccolor/blob/2461074ce39527b7cdebbd0eab5bb009038cf600/latex/cinematic-color.tex#L37) uses pure tabs, it is maybe something we should all agree on and put in the README file?

Right now I'm using 4 spaces and 79 characters line length, will push on Slack for further discussion.

**Comment by aforsythe** [comment]
updated formatting of the source and made modifications to the commit message

**Comment by aforsythe** [comment]
Sorry about the force ... missed something and didn't want to just keep putting lots of small commits on top of each other.

**Comment by thomasmansencal** [comment]
LGTM!

**Pull request merged**
